# Generated by Django 4.1.2 on 2022-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_author_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
    ]
